import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Picture } from '../components/Picture';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to the sidepix component!
                </h1>

                <Picture
                    sources={{
                        '(min-width: 840px)': {
                            aspectRatio: 2,
                            widths: [800, 1200],
                            sizes: {
                                '(min-width: 1240px)': '1200px',
                                default: '800px',
                            },
                        },
                        '(min-width: 640px)': {
                            widths: [600],
                            aspectRatio: 2 / 3,
                            sizes: {
                                default: '600px',
                            },
                        },
                        default: {
                            src: 'test-picture.jpg',
                            aspectRatio: 1,
                            focalPoint: [0.46, 0.14],
                            widths: [400],
                            sizes: {
                                default: '400px',
                            },
                        },
                    }}
                    alt="Black and Green Toucan on Tree Branch"
                />

            </main>
        </div>
    )
}

export default Home
